# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{woulda}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean Hussey", "Josh Nichols"]
  s.date = %q{2011-09-29}
  s.description = %q{TODO}
  s.email = ["sean@seanhussey.com", "josh@technicalpickles.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION.yml",
    "lib/woulda.rb",
    "lib/woulda/acts_as_ferret.rb",
    "lib/woulda/acts_as_ferret/macros.rb",
    "lib/woulda/acts_as_list.rb",
    "lib/woulda/acts_as_list/macros.rb",
    "lib/woulda/acts_as_paranoid.rb",
    "lib/woulda/acts_as_paranoid/macros.rb",
    "lib/woulda/acts_as_solr.rb",
    "lib/woulda/acts_as_solr/macros.rb",
    "lib/woulda/acts_as_state_machine.rb",
    "lib/woulda/acts_as_state_machine/macros_new.rb",
    "lib/woulda/acts_as_state_machine/macros_old.rb",
    "lib/woulda/acts_as_taggable_on_steroids.rb",
    "lib/woulda/acts_as_taggable_on_steroids/macros.rb",
    "lib/woulda/acts_as_versioned.rb",
    "lib/woulda/acts_as_versioned/macros.rb",
    "lib/woulda/acts_as_xapian.rb",
    "lib/woulda/acts_as_xapian/macros.rb",
    "lib/woulda/attachment_fu.rb",
    "lib/woulda/attachment_fu/macros.rb",
    "lib/woulda/enumerations_mixin.rb",
    "lib/woulda/enumerations_mixin/macros.rb",
    "lib/woulda/lazy_http.rb",
    "lib/woulda/lazy_http/macros.rb",
    "lib/woulda/paperclip.rb",
    "lib/woulda/paperclip/macros.rb",
    "lib/woulda/should_raise.rb",
    "lib/woulda/should_raise/macros.rb",
    "lib/woulda/will_paginate.rb",
    "lib/woulda/will_paginate/macros.rb",
    "lib/woulda/woulda_workflow.rb",
    "lib/woulda/woulda_workflow/macros.rb",
    "shoulda_macros/woulda_macros.rb"
  ]
  s.homepage = %q{http://github.com/seanhussey/woulda}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{woulda is a home for shoulda macros that don't belong in the main shoulda library}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["= 2.1.1"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rails>, ["= 2.1.1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rails>, ["= 2.1.1"])
  end
end

